name: mcd_point_tracker
description: A point tracking dashboard for rewards and manual review flows.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^16.3.0
  go_router: ^13.2.2
  intl: ^0.18.1
  image: ^4.1.3
  permission_handler: ^11.3.0
  photo_manager: ^2.7.2
  path: ^1.9.0
  google_mlkit_text_recognition: ^0.13.0
  path_provider: ^2.1.3
  crypto: ^3.0.3
  sqflite: ^2.3.3
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
